name: Archive SVG

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: archive stats image
        run: |
          curl --retry 3 -o github-stats-full.svg "https://raw.githubusercontent.com/cn-kali-team/github-stats/master/generated/overview.svg"
          curl --retry 3 -o github-langs.svg "https://raw.githubusercontent.com/cn-kali-team/github-stats/master/generated/languages.svg"
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: cn-kali-team
          author_email: root@kali-team.cn
          message: 'archive svg'
          add: '*.svg'
